### ISSUE TITLE
Redirect loop when click on a wrong link

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#186]
Reproduce : Go to docs homepage --> ``Try it now`` button --> Checkout `configuration` 

You'll see a redirect loop here. 

Basicly, browser will redirect you to `/statinamic/usage/configuration/` instead of `/statinamic/docs/usage/configuration/`

**Comment by thangngoc89** [comment]
Or even better. Go to any un-real link http://moox.io/statinamic/fsdfsdf

**Comment by MoOx** [comment]
Ouch. I didn't think about the fact that the 404.html is trying to get data for itself.

**Comment by thangngoc89** [comment]
So many trouble with catch-links

**Comment by MoOx** [comment]
It's not related to catch links at all.

Link is not wrong, it's missing a trailing slash. `Try it now` > /statinamic/docs/setup (no trailing slash). So the relative link is wrong. So that's one bug.

The other is the 404 component which try to get some data for an url that is not registered, so this create a loop.

**Comment by thangngoc89** [comment]
Thanks. I get it.

**Comment by MoOx** [comment]
So 2 things to fix:

- handle trailing slash auto redirection
- 404 should not try to get data.
