### ISSUE TITLE
Don't use 0.0.0.0 as default devHost on windows

### ISSUE THREAD

**Issue by thangngoc89** [MoOx/statinamic#257]
Windows doesn't resolve 0.0.0.0 as localhost/127.0.0.1

[process.platform](https://nodejs.org/api/process.html#process_process_platform) will help us

**Comment by thangngoc89** [comment]
Or we can seperate server's host and `opn`'s host. I personally don't like this because this mean more code to maintaince.

**Comment by MoOx** [comment]
Maybe we can just use localhost by default for "opn". Anyway, people are not likely to change this since the server is local, opening it on localhost is the only thing that make sense, right?
Listening to 0.0.0.0 make sense to open on other devices, but opening on other devices is (for now haha) only manual.
I don't know if user will really want to change this parameter (eg: only listen on a specific ip/hostname), or only "opn" on a specific ip/hostname too.

So I think we should just "opn" on localhost by default, and do not have platform specific code by default (make maintenance/tests more complicated).

**Comment by MoOx** [comment]
Btw, how did you test this issue if you don't have windows?

**Comment by thangngoc89** [comment]
I thought about only change opn host before. But will it break wepack hot reload?

Ah. I know about this issue via my friend
