### ISSUE TITLE
Rename boilerplate "Layout" component to something more descriptive

### ISSUE THREAD

**Issue by mxstbr** [MoOx/statinamic#80]
It took me a good minute or two of searching and finding the `import` in the `app/routes.js` file to understand that the `Layout` component of the boilerplate is the wrapper around all routes.

Renaming it to `Wrapper`, `App` or something to that effect should happen, because it's very unclear from the naming alone what the component does.

**Comment by MoOx** [comment]
Yeah. Thanks for opening discussion like this. I think it's unclear too.
Here are some idea (I would like to avoid words that are too generic like "wrapper" or "app")

- GlobalLayout
- WrapperLayout
- AppLayout
- AppWrapper
- AppComponent
- WrapperComponent
- App

At the end, it's the "application wrapper component" so we should take something from that list.

If we remove the word "layout" which make sense, I will continue this discussion with this:
@magsout reported to me that using the word "layout" is a bit weird for page "layouts". I chose this one because jekyll use it... (and statinamic was called "reactyll" during my first wip...).
Do you have any better idea?

**Comment by MoOx** [comment]
Maybe "layout" should be "template"? I never liked this word (template) but that's an idea.

**Comment by magsout** [comment]
> Here are some idea (I would like to avoid words that are too generic like "wrapper" or "app")

`App` or `Main` make sens for me, it's the first folder that I open. Like `index.js` when I open a component folder.

>At the end, it's the "application wrapper component" so we should take something from that list.

So if you are not happy/ok/convince, `AppWrapper` comes closest to the idea of what this directory

**Comment by magsout** [comment]
>Maybe "layout" should be "template"? I never liked this word (template) but that's an idea.

In `layout` I expect to find pages: Homepage, Contact, Account etc ..

**Comment by mxstbr** [comment]
Wouldn't "LayoutWrapper" make sense if we keep calling page layouts `layout`s? Because that's what it does, it's a wrapper all `layout`s. (Or "TemplateWrapper")

**Comment by MoOx** [comment]
LayoutWrapper lgtm. Will do.

**Comment by mxstbr** [comment]
I actually like `layout`, I think it makes sense. I went ahead and created a PR that renames `Layout` to `LayoutWrapper`, see #84

**Comment by MoOx** [comment]
I was thinking about the word "container". I found it clear about the fact that it's a wrapper or an interesting thing :)
"Container" ? "LayoutContainer" ? "AppContainer"?

**Comment by mxstbr** [comment]
Ohhh I like `LayoutContainer`!

**Comment by mxstbr** [comment]
Updated #84

**Comment by MoOx** [comment]
@mxstbr I made a rebase commit like it was you :) https://github.com/MoOx/statinamic/commit/27e492552da43a53b3712c3a7fcccc2d47b901ad
